org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
fabric_loader_version=0.19.5
fabric_api_version=0.116.17+1.21.1

mod_id=dedsafio4remake
mod_name=Dedsafio 4 Remake
mod_license=LGPL-3.0-only
mod_version=1.0.0
mod_group_id=com.alvaro842.remake
mod_authors=alvaro842
mod_description=Recreación de la animación del cielo en Dedsafio 4
